/**
 * Cours réels par profil scolaire (table `courses`).
 *
 * Ces cours sont ORIGINAUX et servis SANS dépendre de l'IA. Ils sont
 * volontairement distincts par classe (6ᵉ ≠ 3ᵉ), par voie (générale/techno) et
 * par spécialité (ex. NSI) — jamais une simple duplication.
 *
 * Champs : subject (slug), countryCode, level, grade, track, specialties,
 * chapter, title, objective, prerequisites, sections, examples, method,
 * commonMistakes, exercise, correction, quiz, summary, flashcards,
 * difficulty, language, source, status.
 */

const q = (text, options, answer, explanation) => ({ text, options, answer, explanation });
const s = (heading, content) => ({ heading, content });
const card = (front, back) => ({ front, back });

export const COURSE_SEED = [
  /* ============================ COLLÈGE — MATHS ============================ */
  {
    subject: 'maths', countryCode: 'FR', level: 'college', grade: '6eme', track: '', specialties: [],
    chapter: 'Nombres et calculs — décimaux', title: '6ème · Nombres décimaux',
    objective: 'Lire, écrire, comparer et ranger les nombres décimaux.',
    prerequisites: ['Nombres entiers', 'Valeur de position des chiffres'],
    sections: [
      s('Écriture décimale', 'Un nombre décimal s’écrit avec une virgule : 12,45. La partie entière est avant la virgule, la partie décimale après. Les rangs après la virgule sont : dixièmes, centièmes, millièmes.'),
      s('Comparer et ranger', 'On compare d’abord les parties entières ; si elles sont égales, on compare chiffre à chiffre après la virgule. Ranger, c’est écrire dans l’ordre croissant ou décroissant.'),
    ],
    examples: ['12,45 = 12 + 4/10 + 5/100', '1,2 > 1,02 car 2 dixièmes > 0 dixième'],
    method: '1) Écris les nombres alignés par leur virgule. 2) Compare la partie entière. 3) Si besoin, ajoute des zéros pour comparer les décimales.',
    commonMistakes: ['Croire que 1,2 < 1,15 (car 15 > 2)', 'Oublier que 0,7 = 7/10'],
    exercise: 'Range dans l’ordre croissant : 3,07 ; 3,7 ; 3,007 ; 3,17.',
    correction: '3,007 < 3,07 < 3,17 < 3,7. On compare les dixièmes, puis les centièmes, puis les millièmes.',
    quiz: [
      q('Combien de dixièmes y a-t-il dans 2,4 ?', ['4', '24', '0,4', '2'], 1, '2,4 = 24/10 : il y a 24 dixièmes.'),
      q('Quel est le plus grand ?', ['1,02', '1,2', '1,022', '1,002'], 1, 'On compare les dixièmes : 2 > 0.'),
    ],
    summary: 'Un décimal se lit rang par rang après la virgule. Pour comparer, on part de la partie entière puis des dixièmes, centièmes, millièmes.',
    flashcards: [card('0,5 en fraction', '1/2 (5 dixièmes)'), card('Rang après la virgule n°1', 'Les dixièmes'), card('1,2 ou 1,02 ?', '1,2 est plus grand.')],
    difficulty: 'easy', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'college', grade: '6eme', track: '', specialties: [],
    chapter: 'Nombres et calculs — fractions', title: '6ème · Fractions simples',
    objective: 'Comprendre une fraction comme un partage et comparer des fractions simples.',
    prerequisites: ['Nombres entiers', 'Partages en parts égales'],
    sections: [
      s('Fraction = partage', '3/4 signifie : le tout est partagé en 4 parts égales et on en prend 3. Le dénominateur (en bas) indique le nombre de parts, le numérateur (en haut) le nombre de parts prises.'),
      s('Comparer', 'Pour un même numérateur, plus le dénominateur est grand, plus la part est petite : 1/3 < 1/2.'),
    ],
    examples: ['La moitié d’un gâteau : 1/2', '3/4 de 20 = 20 ÷ 4 × 3 = 15'],
    method: 'Pour prendre une fraction d’une quantité : divise par le dénominateur, puis multiplie par le numérateur.',
    commonMistakes: ['Inverser numérateur et dénominateur', 'Croire que 1/3 > 1/2'],
    exercise: 'Calcule les 2/5 de 35 €.',
    correction: '35 ÷ 5 = 7, puis 7 × 2 = 14. Les 2/5 de 35 € valent 14 €.',
    quiz: [
      q('1/2 + 1/2 = ?', ['1/4', '1', '2/4', '1/2'], 1, 'Deux moitiés forment un tout.'),
      q('Compare 1/3 et 1/2.', ['1/3 > 1/2', '1/3 < 1/2', 'égales', 'impossible'], 1, 'Plus le dénominateur est grand, plus la part est petite.'),
    ],
    summary: 'Une fraction représente un partage. Pour comparer, compare la taille des parts ; pour calculer une fraction d’une quantité, divise puis multiplie.',
    flashcards: [card('Un quart', '1/4 : le tout partagé en 4 parts égales'), card('3/4 de 20', '15'), card('1/3 vs 1/2', '1/3 < 1/2')],
    difficulty: 'easy', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'college', grade: '5eme', track: '', specialties: [],
    chapter: 'Nombres et calculs — relatifs', title: '5ème · Nombres relatifs',
    objective: 'Utiliser les nombres négatifs, les placer et les additionner.',
    prerequisites: ['Nombres décimaux (6ème)', 'Droite graduée'],
    sections: [
      s('Positif, négatif', 'Un nombre relatif possède un signe. Sur une droite graduée, les négatifs sont à gauche de 0, les positifs à droite. -3 et +3 sont opposés.'),
      s('Additionner', 'Même signe : on additionne et on garde le signe (−2 + −5 = −7). Signes contraires : on soustrait et on garde le signe du plus « fort » (−2 + 5 = +3).'),
    ],
    examples: ['−4 + 6 = 2', '−7 + 3 = −4', 'Sur une droite, −2 est plus petit que 1'],
    method: 'Place toujours les nombres sur une droite ou utilise la règle des signes : même signe → somme, signe contraire → différence.',
    commonMistakes: ['Additionner sans tenir compte des signes', 'Confondre « plus grand » et « plus loin de 0 » (−5 < −2)'],
    exercise: 'Calcule : −8 + 3 + 5 − 4.',
    correction: '−8 + 3 = −5 ; −5 + 5 = 0 ; 0 − 4 = −4. Le résultat est −4.',
    quiz: [
      q('−5 + 2 = ?', ['−3', '3', '−7', '7'], 0, 'Signes contraires : 5 − 2 = 3, on garde le signe du plus grand, donc −3.'),
      q('Quel nombre est le plus petit ?', ['−2', '−7', '0', '1'], 1, 'Sur une droite graduée, −7 est le plus à gauche.'),
    ],
    summary: 'Les nombres relatifs ont un signe. On les additionne selon la règle des signes et on les compare sur une droite graduée.',
    flashcards: [card('Opposé de −4', '4'), card('−2 + 5', '3'), card('Le plus petit : −1 ou −8 ?', '−8')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'college', grade: '5eme', track: '', specialties: [],
    chapter: 'Organisation et gestion de données — proportionnalité', title: '5ème · Proportionnalité',
    objective: 'Reconnaître une situation proportionnelle et calculer une quatrième proportionnelle.',
    prerequisites: ['Fractions simples (6ème)', 'Opérations sur les décimaux'],
    sections: [
      s('Reconnaître la proportionnalité', 'Deux grandeurs sont proportionnelles si l’on passe de l’une à l’autre en multipliant toujours par le même nombre (coefficient de proportionnalité).'),
      s('Calculer', 'On utilise le coefficient, le passage à l’unité ou le produit en croix : a/b = c/d donne a × d = b × c.'),
    ],
    examples: ['1 kg coûte 3 € → 4 kg coûtent 12 €', '50 km en 1 h → 200 km en 4 h'],
    method: 'Cherche d’abord « combien pour 1 », puis multiplie. Pour vérifier, compare les quotients.',
    commonMistakes: ['Appliquer la proportionnalité à tort (ex. âge/taille)', 'Se tromper de sens dans le produit en croix'],
    exercise: '3 stylos coûtent 4,50 €. Combien coûtent 7 stylos ?',
    correction: '1 stylo = 4,50 ÷ 3 = 1,50 €. 7 stylos = 1,50 × 7 = 10,50 €.',
    quiz: [
      q('5 pains coûtent 6 €. Combien coûte 1 pain ?', ['0,83 €', '1,20 €', '1,50 €', '6 €'], 1, '6 ÷ 5 = 1,20 €.'),
      q('Une situation proportionnelle se reconnaît à :', ['un coefficient constant', 'des nombres pairs', 'une addition', 'une moyenne'], 0, 'On multiplie toujours par le même coefficient.'),
    ],
    summary: 'Proportionnalité = coefficient constant. On passe par l’unité ou le produit en croix pour trouver une valeur manquante.',
    flashcards: [card('Coefficient de proportionnalité', 'Le nombre par lequel on multiplie pour passer d’une grandeur à l’autre'), card('3 stylos à 4,50 € → 1 stylo', '1,50 €'), card('Produit en croix', 'a/b = c/d ⟺ a × d = b × c')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'college', grade: '4eme', track: '', specialties: [],
    chapter: 'Géométrie — Pythagore', title: '4ème · Théorème de Pythagore',
    objective: 'Calculer une longueur dans un triangle rectangle avec le théorème de Pythagore.',
    prerequisites: ['Carrés et racines carrées (5ème)', 'Triangle rectangle'],
    sections: [
      s('Le théorème', 'Dans un triangle rectangle, le carré de l’hypoténuse est égal à la somme des carrés des deux autres côtés : AB² + AC² = BC² (BC = hypoténuse).'),
      s('Deux usages', 'Calculer l’hypoténuse : BC = √(AB² + AC²). Calculer un côté : AB = √(BC² − AC²). Réciproque : si l’égalité est vraie, le triangle est rectangle.'),
    ],
    examples: ['Si AB = 3 et AC = 4, alors BC = √(9 + 16) = 5', 'Réciproque : 6² + 8² = 10² → triangle rectangle'],
    method: 'Repère l’hypoténuse (face à l’angle droit), puis applique la formule dans le bon sens.',
    commonMistakes: ['Additionner au lieu de soustraire pour un côté de l’angle droit', 'Appliquer le théorème hors d’un triangle rectangle'],
    exercise: 'Un triangle rectangle a pour hypoténuse 13 cm et un côté 5 cm. Quelle est la longueur du troisième côté ?',
    correction: '√(13² − 5²) = √(169 − 25) = √144 = 12 cm.',
    quiz: [
      q('Dans un triangle rectangle, l’hypoténuse est :', ['le plus petit côté', 'le côté face à l’angle droit', 'un côté de l’angle droit', 'la hauteur'], 1, 'L’hypoténuse est toujours face à l’angle droit.'),
      q('Côtés 6 et 8 : hypoténuse ?', ['10', '14', '48', '100'], 0, '√(36 + 64) = √100 = 10.'),
    ],
    summary: 'Pythagore relie les trois côtés d’un triangle rectangle. On ajoute pour l’hypoténuse, on soustrait pour un côté de l’angle droit.',
    flashcards: [card('Formule de Pythagore', 'AB² + AC² = BC²'), card('Côtés 3 et 4', 'Hypoténuse = 5'), card('Réciproque', 'Si a² + b² = c², le triangle est rectangle.')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'college', grade: '4eme', track: '', specialties: [],
    chapter: 'Nombres et calculs — puissances', title: '4ème · Puissances de 10',
    objective: 'Utiliser les puissances de 10 et la notation scientifique.',
    prerequisites: ['Nombres décimaux (6ème)', 'Multiplier par 10, 100, 1000'],
    sections: [
      s('Puissances de 10', '10³ = 10 × 10 × 10 = 1000. 10⁻² = 1/10² = 0,01. L’exposant indique le nombre de zéros (ou de rangs après la virgule).'),
      s('Notation scientifique', 'Tout nombre s’écrit a × 10ⁿ avec 1 ≤ a < 10. Exemple : 45 000 = 4,5 × 10⁴.'),
    ],
    examples: ['3,2 × 10³ = 3200', '0,005 = 5 × 10⁻³', '10⁴ × 10² = 10⁶'],
    method: 'Multiplier par 10ⁿ décale la virgule de n rangs vers la droite (n > 0) ou vers la gauche (n < 0).',
    commonMistakes: ['Confondre 10³ et 1000 × 3', 'Mal placer la virgule en notation scientifique'],
    exercise: 'Écris 0,00072 en notation scientifique.',
    correction: '0,00072 = 7,2 × 10⁻⁴.',
    quiz: [
      q('10³ = ?', ['30', '100', '1000', '300'], 2, '10 × 10 × 10 = 1000.'),
      q('45 000 en notation scientifique :', ['45 × 10³', '4,5 × 10⁴', '0,45 × 10⁵', '4,5 × 10³'], 1, 'Il faut 1 ≤ a < 10 : 4,5 × 10⁴.'),
    ],
    summary: 'Une puissance de 10 compte les zéros. La notation scientifique place un chiffre avant la virgule et utilise une puissance de 10.',
    flashcards: [card('10⁻²', '0,01'), card('45 000 = ?', '4,5 × 10⁴'), card('10⁴ × 10²', '10⁶ (on additionne les exposants)')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'college', grade: '3eme', track: '', specialties: [],
    chapter: 'Géométrie — Thalès', title: '3ème · Théorème de Thalès',
    objective: 'Calculer une longueur avec le théorème de Thalès dans une configuration de droites parallèles.',
    prerequisites: ['Théorème de Pythagore (4ème)', 'Proportionnalité (5ème)', 'Droites parallèles'],
    sections: [
      s('Configuration', 'Si (BC) ∥ (DE) et que les droites (BD) et (CE) se coupent en A, alors on a une configuration de Thalès en « papillon » ou « triangle emboîté ».'),
      s('Égalité de Thalès', 'AB/AD = AC/AE = BC/DE. On utilise le produit en croix pour trouver une longueur inconnue.'),
    ],
    examples: ['AB = 3, AD = 6, BC = 2 → DE = 4', 'Réciproque : si les rapports sont égaux, alors les droites sont parallèles'],
    method: '1) Vérifie la présence de deux droites parallèles. 2) Écris les rapports en alignant les points de même côté. 3) Produit en croix.',
    commonMistakes: ['Appliquer Thalès sans droites parallèles', 'Inverser les rapports (AD/AB au lieu de AB/AD)', 'Confondre avec Pythagore'],
    exercise: 'Dans un triangle ABC, D ∈ [AB], E ∈ [AC], (DE) ∥ (BC). AB = 5 cm, AD = 2 cm, BC = 7,5 cm. Calcule DE.',
    correction: 'AD/AB = DE/BC → 2/5 = DE/7,5 → DE = 7,5 × 2 ÷ 5 = 3 cm.',
    quiz: [
      q('Condition indispensable pour Thalès :', ['deux droites parallèles', 'un angle droit', 'un cercle', 'une médiane'], 0, 'Sans droites parallèles, Thalès ne s’applique pas.'),
      q('Si (BC) ∥ (DE) :', ['AB/AD = AC/AE = BC/DE', 'AB/AD = DE/BC', 'AB × AD = AC × AE', 'AB + AD = AC + AE'], 0, 'Les rapports de longueurs correspondants sont égaux.'),
    ],
    summary: 'Thalès compare des longueurs dès qu’il y a des droites parallèles. On écrit les rapports dans le bon ordre puis on fait un produit en croix.',
    flashcards: [card('Égalité de Thalès', 'AB/AD = AC/AE = BC/DE'), card('Condition clé', 'Deux droites parallèles'), card('Réciproque de Thalès', 'Rapports égaux → droites parallèles')],
    difficulty: 'hard', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'college', grade: '3eme', track: '', specialties: [],
    chapter: 'Nombres et calculs — calcul littéral', title: '3ème · Calcul littéral : développer et factoriser',
    objective: 'Développer, factoriser et réduire des expressions littérales.',
    prerequisites: ['Distributivité simple', 'Nombres relatifs (5ème)'],
    sections: [
      s('Développer', 'Simple : k(a + b) = ka + kb. Double : (a + b)(c + d) = ac + ad + bc + bd.'),
      s('Identités remarquables', '(a + b)² = a² + 2ab + b² ; (a − b)² = a² − 2ab + b² ; a² − b² = (a − b)(a + b).'),
    ],
    examples: ['(x + 3)(x − 2) = x² + x − 6', 'x² − 9 = (x − 3)(x + 3)', '2x + 3x − x = 4x'],
    method: 'Développer : applique la distributivité puis réduis. Factoriser : cherche un facteur commun ou une identité remarquable.',
    commonMistakes: ['(x + 3)² = x² + 9 (oubli du double produit)', 'Signes lors du développement de −2(x − 5)'],
    exercise: 'Développe et réduis (2x − 1)(x + 4).',
    correction: '2x·x + 2x·4 − 1·x − 1·4 = 2x² + 8x − x − 4 = 2x² + 7x − 4.',
    quiz: [
      q('(x + 3)(x − 2) = ?', ['x² + x − 6', 'x² − x − 6', 'x² + 5x − 6', 'x² − 6'], 0, 'x² − 2x + 3x − 6 = x² + x − 6.'),
      q('x² − 9 = ?', ['(x − 3)²', '(x − 3)(x + 3)', '(x − 9)(x + 1)', 'x(x − 9)'], 1, 'Différence de deux carrés.'),
    ],
    summary: 'Développer, c’est transformer un produit en somme ; factoriser l’inverse. Les identités remarquables font gagner du temps.',
    flashcards: [card('(a + b)²', 'a² + 2ab + b²'), card('a² − b²', '(a − b)(a + b)'), card('−2(x − 5)', '−2x + 10')],
    difficulty: 'hard', language: 'fr', source: 'seed', status: 'published',
  },

  /* ========================== COLLÈGE — FRANÇAIS ========================== */
  {
    subject: 'francais', countryCode: 'FR', level: 'college', grade: '6eme', track: '', specialties: [],
    chapter: 'Grammaire — nature des mots', title: '6ème · Les classes de mots',
    objective: 'Identifier la classe grammaticale d’un mot dans une phrase simple.',
    prerequisites: ['Lire une phrase simple'],
    sections: [
      s('Les mots variables', 'Nom (chat, maison), déterminant (le, une), adjectif (petit, belle), verbe (dort, mange), pronom (il, elle).'),
      s('Les mots invariables', 'Adverbe (vite, très), préposition (à, dans), conjonction (et, mais), interjection.'),
    ],
    examples: ['« Le chat noir dort » : Le = déterminant, chat = nom, noir = adjectif, dort = verbe'],
    method: 'Observe ce que le mot fait dans la phrase : désigne-t-il ? qualifie-t-il ? exprime-t-il une action ?',
    commonMistakes: ['Confondre adjectif et adverbe (rapide / vite)', 'Prendre le déterminant pour un nom'],
    exercise: 'Donne la classe de chaque mot : « Une petite fille chante doucement. »',
    correction: 'Une = déterminant, petite = adjectif, fille = nom, chante = verbe, doucement = adverbe.',
    quiz: [
      q('« vite » est un…', ['adjectif', 'adverbe', 'nom', 'verbe'], 1, '« Vite » modifie le verbe : adverbe.'),
      q('Dans « une belle maison », « maison » est un…', ['adjectif', 'nom', 'verbe', 'déterminant'], 1, 'Il désigne un objet : nom commun.'),
    ],
    summary: 'Chaque mot a une nature (classe). On la reconnaît à son rôle dans la phrase, pas à son sens isolé.',
    flashcards: [card('Adjectif', 'Qualifie le nom : « un petit chat »'), card('Adverbe', 'Invariable, modifie le verbe : « il court vite »'), card('Déterminant', 'Devant le nom : le, une, mon…')],
    difficulty: 'easy', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'francais', countryCode: 'FR', level: 'college', grade: '6eme', track: '', specialties: [],
    chapter: 'Conjugaison — présent', title: '6ème · Le présent des verbes du 1er groupe',
    objective: 'Conjuguer au présent de l’indicatif les verbes en -er.',
    prerequisites: ['Reconnaître l’infinitif'],
    sections: [
      s('Terminaisons', 'je -e, tu -es, il/elle -e, nous -ons, vous -ez, ils/elles -ent.'),
      s('Cas particulier', 'Devant « ons », les verbes en -ger gardent le « e » (nous mangeons) et les verbes en -cer prennent une cédille (nous commençons).'),
    ],
    examples: ['je chante, tu chantes, il chante, nous chantons, vous chantez, ils chantent'],
    method: 'Retire -er de l’infinitif, ajoute la terminaison correspondant au sujet.',
    commonMistakes: ['« nous mangons » au lieu de « nous mangeons »', 'Oublier le -s à « tu »'],
    exercise: 'Conjugue « commencer » à la 1re personne du pluriel au présent.',
    correction: 'Nous commençons (cédille devant « ons »).',
    quiz: [
      q('« Nous (manger) » au présent :', ['nous mangons', 'nous mangeons', 'nous mangions', 'nous mangerons'], 1, 'On garde le e après g devant ons.'),
      q('Terminaison de « tu » (1er groupe) :', ['-e', '-es', '-s', '-ez'], 1, 'Tu chantes : -es.'),
    ],
    summary: 'Le présent du 1er groupe suit des terminaisons régulières, avec deux pièges : -ger et -cer.',
    flashcards: [card('Terminaisons du présent (1er groupe)', '-e, -es, -e, -ons, -ez, -ent'), card('nous (manger)', 'nous mangeons'), card('nous (commencer)', 'nous commençons')],
    difficulty: 'easy', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'francais', countryCode: 'FR', level: 'college', grade: '5eme', track: '', specialties: [],
    chapter: 'Lecture et écriture — le récit', title: '5ème · Le récit et l’imparfait',
    objective: 'Distinguer récit et description et employer correctement l’imparfait.',
    prerequisites: ['Le présent de l’indicatif (6ème)', 'Notion de narrateur'],
    sections: [
      s('Récit et description', 'Le récit raconte des actions (souvent au passé simple) ; la description plante le décor (souvent à l’imparfait).'),
      s('L’imparfait', 'Terminaisons : -ais, -ais, -ait, -ions, -iez, -aient. Radical = « nous » au présent sans -ons.'),
    ],
    examples: ['Il marchait (description) puis il aperçut une ombre (action)', 'nous finissions → je finissais'],
    method: 'Pour conjuguer : prends « nous » au présent, retire -ons, ajoute la terminaison d’imparfait.',
    commonMistakes: ['Confondre imparfait et passé simple', 'Radical irrégulier de « être » : j’étais'],
    exercise: 'Conjugue « grandir » à l’imparfait, 3e personne du singulier.',
    correction: 'Nous grandissons → il grandissait.',
    quiz: [
      q('L’imparfait sert surtout à :', ['décrire', 'indiquer une action brève', 'donner un ordre', 'poser une question'], 0, 'Il décrit le décor ou une action qui dure.'),
      q('« vous (finir) » à l’imparfait :', ['vous finissez', 'vous finissiez', 'vous finirez', 'vous finîtes'], 1, 'Vous finissiez.'),
    ],
    summary: 'Le récit alterne actions (passé simple) et descriptions (imparfait). L’imparfait se forme à partir du « nous » au présent.',
    flashcards: [card('Terminaisons de l’imparfait', '-ais, -ais, -ait, -ions, -iez, -aient'), card('Imparfait vs passé simple', 'Description/ durée vs action ponctuelle'), card('j’(être) à l’imparfait', 'j’étais')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'francais', countryCode: 'FR', level: 'college', grade: '4eme', track: '', specialties: [],
    chapter: 'Grammaire — phrase complexe', title: '4ème · La phrase complexe',
    objective: 'Repérer les propositions et distinguer juxtaposition, coordination et subordination.',
    prerequisites: ['Phrase simple', 'Classes de mots (6ème)'],
    sections: [
      s('Juxtaposition et coordination', 'Juxtaposition : propositions séparées par une ponctuation (, ; :). Coordination : reliées par mais, ou, et, donc, or, ni, car.'),
      s('Subordination', 'Une proposition subordonnée dépend d’une proposition principale et est introduite par « que », un pronom relatif ou un mot interrogatif.'),
    ],
    examples: ['Il pleut, je reste (juxtaposition)', 'Je reste car il pleut (coordination)', 'Je crois qu’il pleut (subordination)'],
    method: 'Compte les verbes conjugués : autant de propositions que de verbes conjugués.',
    commonMistakes: ['Oublier qu’il y a autant de propositions que de verbes', 'Confondre coordination et subordination'],
    exercise: 'Combien de propositions dans : « Je pense que tu réussiras, car tu travailles. » ?',
    correction: 'Trois propositions : « Je pense », « que tu réussiras », « car tu travailles ».',
    quiz: [
      q('Relier deux propositions par « car » :', ['juxtaposition', 'coordination', 'subordination', 'apposition'], 1, '« Car » est une conjonction de coordination.'),
      q('Le nombre de propositions égale le nombre de :', ['virgules', 'verbes conjugués', 'noms', 'adjectifs'], 1, 'Un verbe conjugué = une proposition.'),
    ],
    summary: 'Une phrase complexe contient plusieurs propositions, reliées par juxtaposition, coordination ou subordination.',
    flashcards: [card('Coordination', 'mais, ou, et, donc, or, ni, car'), card('Subordination', 'La proposition dépend de la principale'), card('Nombre de propositions', '= nombre de verbes conjugués')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'francais', countryCode: 'FR', level: 'college', grade: '3eme', track: '', specialties: [],
    chapter: 'Grammaire — phrase complexe', title: '3ème · Les propositions subordonnées',
    objective: 'Distinguer subordonnée relative et subordonnée conjonctive.',
    prerequisites: ['Phrase simple et complexe (4ème)', 'Pronoms relatifs'],
    sections: [
      s('Subordonnée relative', 'Introduite par un pronom relatif (qui, que, dont, où…) ; elle complète un nom appelé antécédent.'),
      s('Subordonnée conjonctive', 'Introduite par « que » (conjonction de subordination) ; elle complète un verbe.'),
    ],
    examples: ['Le livre que tu lis est passionnant (relative)', 'Je sais qu’il partira (conjonctive)'],
    method: 'Regarde ce que complète la subordonnée : un nom → relative ; un verbe → conjonctive.',
    commonMistakes: ['Appeler « relative » toute proposition avec « que »', 'Ne pas identifier l’antécédent'],
    exercise: 'Nature de « qui » dans : « L’élève qui travaille réussit. »',
    correction: 'Pronom relatif : « qui travaille » est une subordonnée relative qui complète « l’élève ».',
    quiz: [
      q('Une subordonnée relative est introduite par :', ['un pronom relatif', 'une conjonction de coordination', 'un adverbe', 'un déterminant'], 0, 'Le pronom relatif introduit la relative.'),
      q('Nature de « que » dans « Je sais qu’il part » :', ['pronom relatif', 'conjonction de subordination', 'adverbe', 'préposition'], 1, 'Ici « que » introduit une complétive.'),
    ],
    summary: 'Relative → complète un nom ; conjonctive → complète un verbe. Le mot introducteur et l’antécédent sont les indices clés.',
    flashcards: [card('Relative', 'Introduite par un pronom relatif ; complète un nom'), card('Conjonctive', 'Introduite par « que » ; complète un verbe'), card('Antécédent', 'Le nom que complète la relative')],
    difficulty: 'hard', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'francais', countryCode: 'FR', level: 'college', grade: '3eme', track: '', specialties: [],
    chapter: 'Brevet — compréhension et argumentation', title: '3ème · Brevet : comprendre et argumenter',
    objective: 'Répondre à une question de compréhension et construire une réponse argumentée.',
    prerequisites: ['Lire un texte littéraire', 'Connaître les figures de style de base'],
    sections: [
      s('Répondre à une question', 'On cite le texte (entre guillemets) et on justifie en expliquant l’effet produit. On n’invente pas.'),
      s('Argumenter', 'Une thèse claire, des arguments, et un exemple précis tiré du texte.'),
    ],
    examples: ['« Le champ lexical de la peur (terreur, effroi, tremblement) crée un climat angoissant. »'],
    method: 'Lis la question, surligne les indices dans le texte, puis rédige : idée → citation → explication.',
    commonMistakes: ['Recopier le texte sans expliquer', 'Donner un avis personnel au lieu d’analyser'],
    exercise: 'En une phrase, explique l’effet produit par le champ lexical de la peur.',
    correction: 'Le champ lexical de la peur (terreur, effroi, tremblement) installe une atmosphère angoissante qui prépare le lecteur au drame.',
    quiz: [
      q('Un champ lexical est :', ['des mots liés à une même notion', 'une faute', 'une figure de style', 'un type de phrase'], 0, 'Des mots qui renvoient à une même idée.'),
      q('Une bonne réponse argumentée contient :', ['thèse, arguments, exemples', 'seulement un avis', 'le texte recopié', 'une liste'], 0, 'Thèse + arguments + exemples du texte.'),
    ],
    summary: 'Au Brevet, on cite puis on explique. La réponse argumentée suit : idée, argument, exemple du texte.',
    flashcards: [card('Champ lexical', 'Ensemble de mots liés à une même notion'), card('Méthode de réponse', 'Idée → citation → explication'), card('À éviter', 'Recopier ou donner un avis personnel')],
    difficulty: 'hard', language: 'fr', source: 'seed', status: 'published',
  },

  /* ============================== LYCÉE ============================== */
  {
    subject: 'maths', countryCode: 'FR', level: 'lycee', grade: '2nde', track: '', specialties: [],
    chapter: 'Analyse — fonctions', title: '2nde · Fonctions : lecture et vocabulaire',
    objective: 'Lire une courbe, calculer une image et déterminer un antécédent.',
    prerequisites: ['Calcul littéral (3ème)', 'Repérage dans le plan'],
    sections: [
      s('Image et antécédent', 'f(x) est l’image de x ; x est un antécédent de f(x). Un nombre peut avoir plusieurs antécédents.'),
      s('Variations', 'Une fonction est croissante si elle monte, décroissante si elle descend. On lit les variations sur le tableau de variations.'),
    ],
    examples: ['f(x) = 2x + 1 → f(3) = 7', 'Résoudre 2x + 1 = 5 → x = 2'],
    method: 'Image : remplace x. Antécédent : résous f(x) = y. Variations : lis de gauche à droite.',
    commonMistakes: ['Confondre image et antécédent', 'Oublier qu’un antécédent est la solution d’une équation'],
    exercise: 'Soit f(x) = x² − 4. Trouve les antécédents de 0.',
    correction: 'x² − 4 = 0 → (x − 2)(x + 2) = 0 → x = 2 ou x = −2.',
    quiz: [
      q('f(x) = 3x − 1. f(2) = ?', ['5', '4', '6', '1'], 0, '3 × 2 − 1 = 5.'),
      q('Un antécédent de y par f est :', ['la valeur de f(y)', 'une solution de f(x) = y', 'toujours unique', 'la dérivée'], 1, 'On résout f(x) = y.'),
    ],
    summary: 'Une fonction associe à chaque x une image f(x). Pour un antécédent, on résout une équation.',
    flashcards: [card('Image de 3 par f', 'f(3)'), card('Antécédent de 5', 'x tel que f(x) = 5'), card('Fonction croissante', 'Elle monte quand x augmente')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'francais', countryCode: 'FR', level: 'lycee', grade: '2nde', track: '', specialties: [],
    chapter: 'Argumentation — le texte argumentatif', title: '2nde · Le texte argumentatif',
    objective: 'Reconnaître et produire une argumentation organisée.',
    prerequisites: ['Phrase complexe (4ème)', 'Connecteurs logiques'],
    sections: [
      s('Thèse et arguments', 'La thèse est l’idée défendue ; les arguments la justifient ; les exemples l’illustrent.'),
      s('Organisation', 'Plan dialectique (thèse/antithèse/synthèse) ou thématique, avec des connecteurs (d’abord, ensuite, enfin).'),
    ],
    examples: ['D’abord… ensuite… enfin…', 'Cependant, à l’inverse…'],
    method: 'Annonce la thèse, appuie chaque argument par un exemple, conclus sans répéter.',
    commonMistakes: ['Enchaîner des idées sans exemples', 'Confondre argument et exemple'],
    exercise: 'Rédige deux arguments en faveur de la lecture, chacun avec un exemple.',
    correction: '1) La lecture enrichit le vocabulaire : on y découvre des mots nouveaux en contexte. 2) Elle développe l’empathie : en suivant un personnage, on vit d’autres points de vue.',
    quiz: [
      q('Un exemple dans une argumentation sert à :', ['illustrer un argument', 'remplacer la thèse', 'conclure', 'introduire'], 0, 'L’exemple vient appuyer l’argument.'),
      q('Le plan dialectique est :', ['thèse/antithèse/synthèse', 'début/milieu/fin', 'cause/conséquence', 'lieu/temps'], 0, 'Trois temps de la discussion.'),
    ],
    summary: 'Argumenter = défendre une thèse avec des arguments illustrés d’exemples, organisés par des connecteurs.',
    flashcards: [card('Thèse', 'L’idée que l’on défend'), card('Argument vs exemple', 'L’argument justifie, l’exemple illustre'), card('Connecteur d’opposition', 'Cependant, en revanche, toutefois')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'lycee', grade: '1ere', track: 'general', specialties: [],
    chapter: 'Algèbre — second degré', title: '1ère générale · Équations du second degré',
    objective: 'Résoudre une équation du second degré et étudier le signe d’un trinôme.',
    prerequisites: ['Développer et factoriser (3ème)', 'Fonctions (2nde)'],
    sections: [
      s('Discriminant', 'Pour ax² + bx + c = 0 : Δ = b² − 4ac. Si Δ > 0 : deux solutions ; Δ = 0 : une ; Δ < 0 : aucune.'),
      s('Solutions et signe', 'x = (−b ± √Δ) / 2a. Le trinôme est du signe de a à l’extérieur des racines, du signe opposé entre.'),
    ],
    examples: ['x² − 5x + 6 = 0 → Δ = 1 → x = 2 ou x = 3', 'x² + 1 = 0 → Δ < 0 → aucune solution réelle'],
    method: 'Identifie a, b, c ; calcule Δ ; applique la formule ; vérifie avec la somme et le produit des racines.',
    commonMistakes: ['Se tromper de signe dans Δ', 'Oublier de diviser par 2a', 'Confondre Δ et √Δ'],
    exercise: 'Résous 2x² − 8x + 6 = 0.',
    correction: 'Δ = 64 − 48 = 16 ; √Δ = 4 ; x = (8 ± 4)/4 → x = 3 ou x = 1.',
    quiz: [
      q('Δ de x² − 5x + 6 :', ['1', '−1', '25', '49'], 0, 'Δ = 25 − 24 = 1.'),
      q('Si Δ < 0, l’équation admet :', ['2 solutions', '1 solution', 'aucune solution réelle', 'une infinité'], 2, 'Pas de racine réelle.'),
    ],
    summary: 'Le discriminant décide du nombre de solutions ; les formules donnent les racines et le signe du trinôme.',
    flashcards: [card('Δ', 'b² − 4ac'), card('Solutions', '(−b ± √Δ) / 2a'), card('Δ < 0', 'Aucune solution réelle')],
    difficulty: 'hard', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'francais', countryCode: 'FR', level: 'lycee', grade: '1ere', track: 'general', specialties: [],
    chapter: 'Bac de Français — écrit', title: '1ère générale · Le commentaire de texte',
    objective: 'Construire un commentaire composé organisé en axes.',
    prerequisites: ['Analyse des figures de style', 'Argumentation (2nde)'],
    sections: [
      s('Méthode', 'Lecture attentive → repérage des procédés → axes de lecture → plan détaillé. Chaque axe doit être justifié par des citations analysées.'),
      s('Forme attendue', 'Introduction (présentation, projet de lecture, annonce des axes), développement en 2-3 axes, conclusion.'),
    ],
    examples: ['Axe 1 : une nature mélancolique. Axe 2 : l’expression du temps qui passe.'],
    method: 'Ne raconte jamais le texte : analyse les procédés (lexique, figures, rythme, énonciation) et leur effet.',
    commonMistakes: ['Paraphrase', 'Catalogue de procédés sans effet', 'Axe non appuyé par des citations'],
    exercise: 'Propose deux axes de lecture pour un poème évoquant la fuite du temps.',
    correction: 'Axe 1 : l’omniprésence du temps (lexique, verbes) ; Axe 2 : la mélancolie lyrique (ton, images). Chaque axe sera appuyé par des citations.',
    quiz: [
      q('Un commentaire de texte analyse :', ['les procédés et leurs effets', 'l’histoire de l’auteur', 'l’actualité', 'le résumé'], 0, 'On analyse la forme pour éclairer le sens.'),
      q('La paraphrase consiste à :', ['raconter le texte', 'analyser le style', 'citer', 'comparer'], 0, 'Raconter au lieu d’analyser est un défaut.'),
    ],
    summary: 'Le commentaire suit une méthode : repérage des procédés, axes justifiés par des citations analysées, plan structuré.',
    flashcards: [card('Projet de lecture', 'L’idée directrice du commentaire'), card('Axe de lecture', 'Un angle d’analyse appuyé par des citations'), card('À éviter', 'La paraphrase')],
    difficulty: 'hard', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'informatique', countryCode: 'FR', level: 'lycee', grade: '1ere', track: 'general', specialties: ['NSI'],
    chapter: 'NSI — programmation', title: '1ère générale · NSI : boucles et fonctions',
    objective: 'Écrire et lire un algorithme avec boucles et fonctions (spécialité NSI).',
    prerequisites: ['Affectation et variables', 'Instructions conditionnelles'],
    sections: [
      s('Boucles', 'Boucle bornée « for i in range(n) » répète n fois ; boucle conditionnelle « while » répète tant que la condition est vraie.'),
      s('Fonctions', 'Une fonction regroupe des instructions, reçoit des paramètres et peut renvoyer une valeur (return).'),
    ],
    examples: ['somme = 0 ; for i in range(1, 6): somme += i → 15', 'def double(x): return x * 2'],
    method: 'Décompose le problème en étapes ; choisis la boucle adaptée ; teste avec un petit exemple.',
    commonMistakes: ['Boucle while qui ne s’arrête jamais (condition jamais fausse)', 'Oublier return dans une fonction'],
    exercise: 'Écris une fonction qui renvoie la somme des entiers de 1 à n.',
    correction: 'def somme(n):\n    total = 0\n    for i in range(1, n + 1):\n        total += i\n    return total',
    quiz: [
      q('Quelle boucle répète un nombre de fois connu ?', ['while', 'for', 'if', 'def'], 1, '« for » est bornée.'),
      q('Le mot-clé qui renvoie une valeur :', ['print', 'return', 'input', 'while'], 1, '« return » renvoie le résultat.'),
    ],
    summary: 'En NSI, on structure un algorithme avec des boucles (for/while) et des fonctions qui renvoient une valeur.',
    flashcards: [card('for', 'Boucle bornée : répète n fois'), card('while', 'Boucle conditionnelle : répète tant que c’est vrai'), card('return', 'Renvoie une valeur depuis une fonction')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'lycee', grade: '1ere', track: 'techno', specialties: [],
    chapter: 'Statistiques — pourcentages', title: '1ère technologique · Pourcentages et évolutions',
    objective: 'Calculer et interpréter des pourcentages et des évolutions.',
    prerequisites: ['Proportionnalité (5ème)'],
    sections: [
      s('Pourcentage d’une quantité', 'Prendre t % d’une valeur : multiplier par t/100. Exemple : 15 % de 200 = 30.'),
      s('Évolution', 'Augmenter de t % : multiplier par (1 + t/100). Diminuer de t % : multiplier par (1 − t/100).'),
    ],
    examples: ['Un prix passe de 80 € à 92 € : 92/80 = 1,15 → +15 %', '−20 % puis +20 % ne revient pas au prix initial'],
    method: 'Utilise toujours le coefficient multiplicateur : il s’enchaîne par multiplication.',
    commonMistakes: ['Additionner des pourcentages au lieu de multiplier les coefficients', 'Croire que −20 % puis +20 % annule'],
    exercise: 'Un article à 50 € augmente de 10 %. Quel est le nouveau prix ?',
    correction: '50 × 1,10 = 55 €.',
    quiz: [
      q('Augmenter de 25 %, c’est multiplier par :', ['0,25', '1,25', '25', '0,75'], 1, '1 + 25/100 = 1,25.'),
      q('15 % de 200 :', ['15', '20', '30', '45'], 2, '200 × 0,15 = 30.'),
    ],
    summary: 'Les pourcentages se traduisent en coefficients multiplicateurs, pratiques pour enchaîner des évolutions.',
    flashcards: [card('+25 %', '× 1,25'), card('−10 %', '× 0,90'), card('15 % de 200', '30')],
    difficulty: 'medium', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'maths', countryCode: 'FR', level: 'lycee', grade: 'terminale', track: 'general', specialties: [],
    chapter: 'Analyse — dérivation', title: 'Terminale générale · Dérivation',
    objective: 'Calculer une dérivée et l’utiliser pour étudier les variations.',
    prerequisites: ['Fonctions (2nde)', 'Second degré (1ère)'],
    sections: [
      s('Nombre dérivé', 'f′(a) est le coefficient directeur de la tangente à la courbe au point d’abscisse a.'),
      s('Formules et variations', '(xⁿ)′ = n·xⁿ⁻¹ ; (uv)′ = u′v + uv′. Le signe de f′ donne le sens de variation de f.'),
    ],
    examples: ['(x²)′ = 2x', '(3x + 1)′ = 3', 'f′ > 0 → f croissante'],
    method: 'Pour étudier f : calcule f′, étudie le signe de f′, déduis le tableau de variations, puis les extremums.',
    commonMistakes: ['Oublier le −1 dans l’exposant', 'Conclure sur f au lieu de f′', 'Se tromper dans (uv)′'],
    exercise: 'Étudie les variations de f(x) = x² − 4x + 1.',
    correction: 'f′(x) = 2x − 4. f′(x) = 0 → x = 2. f′ < 0 sur ]−∞ ; 2[ (décroissante), f′ > 0 sur ]2 ; +∞[ (croissante). Minimum en x = 2 : f(2) = −3.',
    quiz: [
      q('Dérivée de x² :', ['x', '2x', 'x²', '2'], 1, '(xⁿ)′ = n·xⁿ⁻¹.'),
      q('Si f′ > 0 sur un intervalle, alors f est :', ['décroissante', 'croissante', 'constante', 'nulle'], 1, 'f′ > 0 signifie que f monte.'),
    ],
    summary: 'La dérivée mesure la variation. Son signe donne les variations de la fonction et permet de trouver les extremums.',
    flashcards: [card('(xⁿ)′', 'n·xⁿ⁻¹'), card('(uv)′', 'u′v + uv′'), card('f′ > 0', 'f croissante')],
    difficulty: 'hard', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'philosophie', countryCode: 'FR', level: 'lycee', grade: 'terminale', track: 'general', specialties: [],
    chapter: 'Bac — Philosophie : la conscience', title: 'Terminale générale · Philosophie : la conscience',
    objective: 'Problématiser la notion de conscience et construire une dissertation.',
    prerequisites: ['Argumentation (2nde)', 'Méthode de la dissertation'],
    sections: [
      s('La notion', 'La conscience est la connaissance immédiate que le sujet a de lui-même et du monde. On distingue conscience spontanée et réflexive (retour sur soi).'),
      s('Problématique', 'Suis-je ce que j’ai conscience d’être ? La conscience révèle-t-elle le sujet ou le masque-t-elle (inconscient) ?'),
    ],
    examples: ['Descartes : le cogito, certitude du sujet pensant', 'Freud : l’hypothèse de l’inconscient limite la transparence du sujet'],
    method: 'Thèse / antithèse / synthèse, chaque partie appuyée par un auteur précis et un exemple.',
    commonMistakes: ['Réciter des auteurs sans répondre au sujet', 'Confondre conscience et connaissance'],
    exercise: 'Formule une problématique pour le sujet : « La conscience de soi est-elle une illusion ? »',
    correction: 'Peut-on se connaître soi-même de façon certaine, ou la conscience est-elle trompeuse et partielle (inconscient, illusions) ?',
    quiz: [
      q('Le cogito est associé à :', ['Descartes', 'Freud', 'Platon', 'Kant'], 0, '« Je pense donc je suis » : Descartes.'),
      q('L’inconscient freudien suggère que :', ['le sujet est totalement transparent', 'la conscience est limitée', 'la conscience n’existe pas', 'tout est rationnel'], 1, 'Il limite la transparence du sujet à lui-même.'),
    ],
    summary: 'La conscience pose la question du rapport du sujet à lui-même : certitude cartésienne contre limites révélées par l’inconscient.',
    flashcards: [card('Cogito', '« Je pense donc je suis » (Descartes)'), card('Conscience réflexive', 'Retour du sujet sur lui-même'), card('Inconscient', 'Hypothèse freudienne limitant la transparence du sujet')],
    difficulty: 'hard', language: 'fr', source: 'seed', status: 'published',
  },
  {
    subject: 'informatique', countryCode: 'FR', level: 'lycee', grade: 'terminale', track: 'general', specialties: ['NSI'],
    chapter: 'NSI — structures de données', title: 'Terminale générale · NSI : listes et dictionnaires',
    objective: 'Manipuler listes et dictionnaires, et choisir la structure adaptée (spécialité NSI).',
    prerequisites: ['Boucles et fonctions (1ère NSI)', 'Indices et itération'],
    sections: [
      s('Listes', 'Une liste est une séquence ordonnée indexée de 0 à n−1. Accès en O(1) par indice, parcours en O(n).'),
      s('Dictionnaires', 'Un dictionnaire associe des clés à des valeurs. Accès par clé, idéal pour compter ou retrouver rapidement une information.'),
    ],
    examples: ['notes = [12, 15, 9] ; notes[0] = 12', 'eleves = {"Léa": 12, "Sam": 15} ; eleves["Sam"] = 15'],
    method: 'Choisis la structure selon l’accès : par position → liste ; par identifiant → dictionnaire.',
    commonMistakes: ['Dépasser les indices d’une liste', 'Utiliser une clé absente d’un dictionnaire'],
    exercise: 'Écris une fonction qui compte les occurrences de chaque lettre d’un mot.',
    correction: 'def compte(mot):\n    d = {}\n    for lettre in mot:\n        d[lettre] = d.get(lettre, 0) + 1\n    return d',
    quiz: [
      q('Accéder au 1er élément d’une liste L :', ['L[1]', 'L[0]', 'L(0)', 'L.first()'], 1, 'Les indices commencent à 0.'),
      q('Le dictionnaire est adapté pour :', ['un accès par clé', 'un tri', 'une file', 'une pile'], 0, 'Clé → valeur.'),
    ],
    summary: 'Listes (accès par indice) et dictionnaires (accès par clé) couvrent la plupart des besoins ; on choisit selon l’usage.',
    flashcards: [card('Liste', 'Séquence ordonnée, index de 0 à n−1'), card('Dictionnaire', 'Associe clé → valeur'), card('d.get(cle, 0)', 'Renvoie 0 si la clé est absente')],
    difficulty: 'hard', language: 'fr', source: 'seed', status: 'published',
  },
];
